plugins {
    id("io.micronaut.build.internal.problem-json-tests-junit")
    id("io.micronaut.build.internal.kotlin-kapt")
}

repositories {
    mavenCentral()
}

dependencies {
    testAnnotationProcessor mnValidation.micronaut.validation.processor
    testAnnotationProcessor(mnSerde.micronaut.serde.processor)
    testImplementation mnValidation.micronaut.validation
    testImplementation libs.kotlin.stdlib.jdk8
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.10.2'
    testImplementation 'io.projectreactor:reactor-core:3.5.0'
    kaptTest mn.micronaut.inject.java
    testImplementation projects.micronautProblemJson
    testImplementation mn.micronaut.http.server.netty
    testImplementation mn.micronaut.http.client
    testImplementation(mnSerde.micronaut.serde.jackson)
}

tasks.named('test') {
    useJUnitPlatform()
}
